### ISSUE TITLE
Support replace table

### ISSUE THREAD

**Issue by rdblue** [Netflix/iceberg#9]
CTAS is often used to replace a result set. If the replacement CTAS fails, users want the previous version of the table to exist. Replacing a table as a single operation would replace all metadata. Like CTAS, this will require a soft-replace that returns a table configured with the new CTAS schema (fresh ids) and partitioning, but that is not committed until the write operation is committed.

**Comment by mike-weinberg** [comment]
> Replacing a table as a single operation would replace all metadata.

Does this have to be true?

if CTAS at t<sub>0</sub> (_C<sub>t_0</sub>_) is a deterministic operation against a snapshot of a dataset D at t<sub>0</sub> (_D<sub>t_0</sub>_), then isn't it possible to preserve metadata whenever the materialization program (e.g. a SQL or perhaps PIG query) does not change, propagating only those changes from any upstream data set?

e.g. if _D<sub>t_1</sub>_'s metadata differs in a way that doesn't change the data (e.g. renames a column), _C<sub>t_1</sub>_ can be considered to use the same materialization program  (_C<sub>p_0</sub>_ e.g. a version of a SQL query or spark program) as _C<sub>t_0</sub>_ specifically because it references ID's and not names in its transformations. 

In other words, if
 _*C<sub>p<sub>t_0</sub></sub> = C<sub>p<sub>t_1</sub></sub> = C<sub>p_0</sub>*_ 
is true, then metadata can be preserved. 

In addition, (I think) it is at minimum _plausible_ to say:
_C<sub>p<sub>t_0</sub></sub> = C<sub>p<sub>t_1</sub></sub>_ 
even in the case of specific data-affecting metadata changes, for example a type promotion from short to long integer (but NOT in the case of a type demotion, which might cause _C<sub>p<sub>t_0</sub></sub>_ to be unsafe)

Seemingly the only time the metadata _could not_ be preserved would be when the relational reference / equivalent of a `FROM` statement is changed such that metadata is only replaced if the data lineage cannot be considered equivalent from one version of the materialization program to the next. 

As for what I'm getting at, I'd like to offer that while metadata replacement is a sensible default operation for CTAS, I think it would be useful to leave room for the possibility that CTAS could be treated as a materialized view, and therefore that metadata replacement is one of multiple reasonable behaviors for table-replacing operations.

**Comment by rdblue** [comment]
@mike-weinberg: no, it doesn't have to be true. That's why there are multiple operations: insert (do not change table metadata), replace/overwrite data (overwrite some/all data, then insert as a single operation), CTAS (create table and insert in one operation) and RTAS (drop, create, and insert in one operation).

Those cover different use cases. If you want to preserve existing metadata, then you should insert or replace data. You would only replace a table if you specifically do not care about compatibility with the previous schema. For example, if you create a report table every day and you want to update the query that produces it, you probably don't want to make DDL changes and then run a job that replaces the contents. You just want to replace whatever is there with a new version with that new version's schema.

For more context, check out the logical plans we are proposing for Spark in the [Standardize Logical Plans SPIP](https://docs.google.com/document/d/1gYm5Ji2Mge3QBdOliFV5gSPTKlX4q1DCBXIkiyMv62A/edit?ts=5a987801#heading=h.ebf4oergd098).

**Comment by mike-weinberg** [comment]
@rdblue thanks for the added context. Metadata history and lineage has been on my mind for a while so I guess my thinking and preferences are biased, but I see what you mean.

**Comment by rdblue** [comment]
This was added in https://github.com/Netflix/iceberg/commit/d2bf0029e44e9d988662f3350a5b903c803b0653.
